name: Shared Checks

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --frozen --all-extras --dev --python 3.12

      - name: Install required packages
        run: pip install python-jose types-python-jose

      - name: Run ruff format check
        run: uv run --no-sync ruff check .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --frozen --all-extras --dev --python 3.12

      - name: Install required packages
        run: pip install python-jose types-python-jose

      - name: Run pyright
        run: uv run --no-sync pyright

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --frozen --all-extras --dev --python ${{ matrix.python-version }}

      - name: Clean existing mcp directory
        run: rm -rf /home/runner/work/python-sdk/python-sdk/src/mcp

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: uv run --no-sync pytest
